// @generated — do not edit by hand.
// Regenerate with: node scripts/generate-model-capabilities.mjs
// Source: scripts/model-capabilities.json

//! Generated model-capability lookup tables.
//!
//! Resolution is a total function `resolve(provider, raw_model_id) → CapabilityResult`.
//! Three ordered steps (plan v4 resolver contract):
//! 1. Provider-qualified raw exact lookup (before any prefix stripping).
//! 2. Provider-scoped ordered family rules on the normalized alias.
//! 3. Per-axis provider fallback (blank vs concrete-unknown).
//!
//! The manifest (scripts/model-capabilities.json) is the single source of truth.
//! This file is regenerated by scripts/generate-model-capabilities.mjs.
//! CI verifies that generated files match the manifest (regenerate-then-diff).
//!
//! Boundaries this file does NOT own (plan v4 §Boundaries):
//! - Transport/endpoint selection for pure OpenAI, legacy Databricks, OpenRouter:
//!   OpenAiApi / openai_request() remain authoritative.
//! - Final display labels: resolveModelLabel() three-tier precedence is authoritative.
//!   `registry_label` here feeds only the static registry tier.
//! - llm.rs replacement scope: ONLY `databricks_v2_route_for_model`.

use crate::config::ThinkingEffort;
use std::borrow::Cow;

/// Which Databricks v2 gateway wire path to use for a model.
/// Scoped to DBv2 only — other providers use `NotApplicable`.
/// Transport for pure OpenAI, legacy Databricks, and OpenRouter is selected
/// by OpenAiApi / openai_request() at runtime, not by this manifest.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DatabricksV2Route {
    /// /ai-gateway/openai/v1/responses
    OpenAiResponses,
    /// /ai-gateway/anthropic/v1/messages
    AnthropicMessages,
    /// /ai-gateway/mlflow/v1/chat/completions
    MlflowChatCompletions,
    /// DBv2 blank model — route not yet determinable.
    RouteUnknown,
    /// Not a DBv2 provider — transport is selected by OpenAiApi/openai_request().
    NotApplicable,
}

/// Anthropic thinking API shape for this model.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ThinkingMode {
    /// thinking:{type:"enabled", budget_tokens} — claude-3*, claude-opus-4-5
    ManualBudget,
    /// thinking:{type:"adaptive"} + output_config:{effort} — opus-4-6+, sonnet-4-6+, etc.
    Adaptive,
    /// Unknown Anthropic model — omit thinking fields rather than guess request shape.
    OmitFields,
    /// Non-Anthropic-routed model — thinking fields are not applicable.
    None,
    /// Provider does not use Anthropic thinking API at all.
    NotApplicable,
}

/// How to normalize effort values before sending to the provider.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NormalizationPolicy {
    /// Pass effort through unchanged.
    None,
    /// Apply per-family effort table; none↔minimal peer fallback + upward tie preference.
    OpenAiStandard,
    /// Unknown OpenAI model: clamp max → xhigh, pass all others unchanged.
    OpenAiClampMaxToXHigh,
}

/// Complete resolved capability record for a (provider, raw_model_id) pair.
/// Every axis is populated — runtime consumers do not compose fields.
#[derive(Debug, Clone, PartialEq)]
pub struct CapabilityResult {
    /// Optional static display label. Feeds resolveModelLabel()'s registry tier only.
    /// The dynamic three-tier precedence (discovered_name > registry_label > raw_id)
    /// lives in formatAgentModelLabel / resolveModelLabel — NOT in this struct.
    pub registry_label: Option<&'static str>,
    /// Anthropic thinking API shape for this model.
    pub thinking_mode: ThinkingMode,
    /// Valid effort values for the model's effort dropdown (UI).
    pub supported_efforts: Cow<'static, [ThinkingEffort]>,
    /// Semantic default, or None when "Inherit" is the natural default (manual-budget Anthropic).
    pub default_effort: Option<ThinkingEffort>,
    /// DBv2 wire route; NotApplicable for non-DBv2 providers.
    pub databricks_v2_wire_route: DatabricksV2Route,
    /// Effort normalization policy before sending to provider.
    pub normalization_policy: NormalizationPolicy,
}

// ---------------------------------------------------------------------------
// Exact records — provider-qualified (provider, raw_model_id), pre-prefix-stripping
// ---------------------------------------------------------------------------

/// Returns the exact capability record for a provider-qualified raw model ID,
/// if one exists in the manifest. This is checked BEFORE any prefix stripping.
pub fn lookup_exact(provider: &str, raw_model_id: &str) -> Option<CapabilityResult> {
    match (provider, raw_model_id) {
        ("databricks_v2", "databricks-gpt-5-4-mini") => {
            // provenance: exact(databricks_v2::databricks-gpt-5-4-mini)
            //   supported_efforts: exact_record
            //   databricks_v2_wire_route: family:openai-gpt5-4@15
            //   thinking_mode: family:openai-gpt5-4@15
            //   normalization_policy: family:openai-gpt5-4@15
            //   default_effort: family:openai-gpt5-4@15
            Some(CapabilityResult {
                registry_label: Some("GPT-5.4 Mini"),
                thinking_mode: ThinkingMode::None,
                supported_efforts: Cow::Borrowed(&[
                    ThinkingEffort::Low,
                    ThinkingEffort::Medium,
                    ThinkingEffort::High,
                ]),
                default_effort: Some(ThinkingEffort::Medium),
                databricks_v2_wire_route: DatabricksV2Route::OpenAiResponses,
                normalization_policy: NormalizationPolicy::OpenAiStandard,
            })
        }
        ("databricks_v2", "databricks-gpt-5-4-nano") => {
            // provenance: exact(databricks_v2::databricks-gpt-5-4-nano)
            //   supported_efforts: exact_record
            //   databricks_v2_wire_route: family:openai-gpt5-4@15
            //   thinking_mode: family:openai-gpt5-4@15
            //   normalization_policy: family:openai-gpt5-4@15
            //   default_effort: family:openai-gpt5-4@15
            Some(CapabilityResult {
                registry_label: Some("GPT-5.4 Nano"),
                thinking_mode: ThinkingMode::None,
                supported_efforts: Cow::Borrowed(&[
                    ThinkingEffort::Low,
                    ThinkingEffort::Medium,
                    ThinkingEffort::High,
                ]),
                default_effort: Some(ThinkingEffort::Medium),
                databricks_v2_wire_route: DatabricksV2Route::OpenAiResponses,
                normalization_policy: NormalizationPolicy::OpenAiStandard,
            })
        }
        ("databricks_v2", "databricks-gpt-5-6-sol") => {
            // provenance: exact(databricks_v2::databricks-gpt-5-6-sol)
            //   supported_efforts: exact_record
            //   databricks_v2_wire_route: family:openai-gpt5-6@15
            //   thinking_mode: family:openai-gpt5-6@15
            //   normalization_policy: family:openai-gpt5-6@15
            //   default_effort: family:openai-gpt5-6@15
            Some(CapabilityResult {
                registry_label: Some("GPT-5.6 Sol"),
                thinking_mode: ThinkingMode::None,
                supported_efforts: Cow::Borrowed(&[
                    ThinkingEffort::None,
                    ThinkingEffort::Low,
                    ThinkingEffort::Medium,
                    ThinkingEffort::High,
                    ThinkingEffort::XHigh,
                    ThinkingEffort::Max,
                ]),
                default_effort: Some(ThinkingEffort::Medium),
                databricks_v2_wire_route: DatabricksV2Route::OpenAiResponses,
                normalization_policy: NormalizationPolicy::OpenAiStandard,
            })
        }
        ("databricks_v2", "databricks-gpt-5-5") => {
            // provenance: exact(databricks_v2::databricks-gpt-5-5)
            //   supported_efforts: family:openai-gpt5-5@15
            //   databricks_v2_wire_route: family:openai-gpt5-5@15
            //   thinking_mode: family:openai-gpt5-5@15
            //   normalization_policy: family:openai-gpt5-5@15
            //   default_effort: family:openai-gpt5-5@15
            Some(CapabilityResult {
                registry_label: Some("GPT-5.5"),
                thinking_mode: ThinkingMode::None,
                supported_efforts: Cow::Borrowed(&[
                    ThinkingEffort::None,
                    ThinkingEffort::Low,
                    ThinkingEffort::Medium,
                    ThinkingEffort::High,
                    ThinkingEffort::XHigh,
                ]),
                default_effort: Some(ThinkingEffort::Medium),
                databricks_v2_wire_route: DatabricksV2Route::OpenAiResponses,
                normalization_policy: NormalizationPolicy::OpenAiStandard,
            })
        }
        ("databricks_v2", "databricks-claude-opus-4-7") => {
            // provenance: exact(databricks_v2::databricks-claude-opus-4-7)
            //   supported_efforts: family:anthropic-adaptive-xhigh-opus-4-7@10
            //   databricks_v2_wire_route: family:anthropic-adaptive-xhigh-opus-4-7@10
            //   thinking_mode: family:anthropic-adaptive-xhigh-opus-4-7@10
            //   normalization_policy: family:anthropic-adaptive-xhigh-opus-4-7@10
            //   default_effort: family:anthropic-adaptive-xhigh-opus-4-7@10
            Some(CapabilityResult {
                registry_label: Some("Claude Opus 4.7"),
                thinking_mode: ThinkingMode::Adaptive,
                supported_efforts: Cow::Borrowed(&[
                    ThinkingEffort::Low,
                    ThinkingEffort::Medium,
                    ThinkingEffort::High,
                    ThinkingEffort::XHigh,
                    ThinkingEffort::Max,
                ]),
                default_effort: Some(ThinkingEffort::High),
                databricks_v2_wire_route: DatabricksV2Route::AnthropicMessages,
                normalization_policy: NormalizationPolicy::None,
            })
        }
        _ => None,
    }
}

// ---------------------------------------------------------------------------
// Family rule resolution — normalized alias after prefix stripping
// ---------------------------------------------------------------------------

/// Strip any catalog-naming prefix to get the normalized model alias for family matching.
/// Finds the first occurrence of a known family token (claude-, gpt-) and returns from there.
///
/// Examples:
///   "goose-claude-fable-5"      → "claude-fable-5"
///   "databricks-gpt-5.5"        → "gpt-5.5"
///   "team-x-claude-opus-4-7"    → "claude-opus-4-7"
///   "claude-opus-4-7"           → "claude-opus-4-7"  (no prefix)
///   "llama-3"                   → "llama-3"           (no family token)
pub fn strip_catalog_prefix(model: &str) -> &str {
    const FAMILY_TOKENS: &[&str] = &["claude-", "gpt-"];
    let lower = model.to_ascii_lowercase();
    let first_idx = FAMILY_TOKENS.iter().filter_map(|tok| lower.find(tok)).min();
    match first_idx {
        Some(idx) => &model[idx..],
        None => model,
    }
}

/// Resolve capability by family rules on the normalized (prefix-stripped) alias.
/// Returns None if no rule matches (caller falls through to provider_fallback).
///
/// Rules are ordered by match_priority descending.
/// Generated from manifest family_rules.
pub fn lookup_by_family_rules(provider: &str, normalized: &str) -> Option<CapabilityResult> {
    let lower = normalized.to_ascii_lowercase();
    let lower = lower.as_str();
    #[allow(clippy::nonminimal_bool)]
    // rule: openai-gpt5-pro, provider: openai, priority: 20
    if provider == "openai"
        && (gpt5_token_matches_rs(lower, "gpt-5-pro") || gpt5_token_matches_rs(lower, "gpt5-pro"))
    {
        return Some(CapabilityResult {
            registry_label: Some("GPT-5 Pro"),
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[ThinkingEffort::High]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::OpenAiStandard,
        });
    }
    // rule: openai-gpt5-pro, provider: databricks_v2, priority: 20
    if provider == "databricks_v2"
        && (gpt5_token_matches_rs(lower, "gpt-5-pro") || gpt5_token_matches_rs(lower, "gpt5-pro"))
    {
        return Some(CapabilityResult {
            registry_label: Some("GPT-5 Pro"),
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[ThinkingEffort::High]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::OpenAiResponses,
            normalization_policy: NormalizationPolicy::OpenAiStandard,
        });
    }
    // rule: openai-gpt5-6, provider: openai, priority: 15
    if provider == "openai"
        && (gpt5_token_matches_rs(lower, "gpt-5.6")
            || gpt5_token_matches_rs(lower, "gpt5.6")
            || gpt5_token_matches_rs(lower, "gpt-5-6")
            || gpt5_token_matches_rs(lower, "gpt5-6"))
    {
        return Some(CapabilityResult {
            registry_label: Some("GPT-5.6"),
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::OpenAiStandard,
        });
    }
    // rule: openai-gpt5-6, provider: databricks_v2, priority: 15
    if provider == "databricks_v2"
        && (gpt5_token_matches_rs(lower, "gpt-5.6")
            || gpt5_token_matches_rs(lower, "gpt5.6")
            || gpt5_token_matches_rs(lower, "gpt-5-6")
            || gpt5_token_matches_rs(lower, "gpt5-6"))
    {
        return Some(CapabilityResult {
            registry_label: Some("GPT-5.6"),
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::OpenAiResponses,
            normalization_policy: NormalizationPolicy::OpenAiStandard,
        });
    }
    // rule: openai-gpt5-5, provider: openai, priority: 15
    if provider == "openai"
        && (gpt5_token_matches_rs(lower, "gpt-5.5")
            || gpt5_token_matches_rs(lower, "gpt5.5")
            || gpt5_token_matches_rs(lower, "gpt-5-5")
            || gpt5_token_matches_rs(lower, "gpt5-5"))
    {
        return Some(CapabilityResult {
            registry_label: Some("GPT-5.5"),
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::OpenAiStandard,
        });
    }
    // rule: openai-gpt5-5, provider: databricks_v2, priority: 15
    if provider == "databricks_v2"
        && (gpt5_token_matches_rs(lower, "gpt-5.5")
            || gpt5_token_matches_rs(lower, "gpt5.5")
            || gpt5_token_matches_rs(lower, "gpt-5-5")
            || gpt5_token_matches_rs(lower, "gpt5-5"))
    {
        return Some(CapabilityResult {
            registry_label: Some("GPT-5.5"),
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::OpenAiResponses,
            normalization_policy: NormalizationPolicy::OpenAiStandard,
        });
    }
    // rule: openai-gpt5-4, provider: openai, priority: 15
    if provider == "openai"
        && (gpt5_token_matches_rs(lower, "gpt-5.4")
            || gpt5_token_matches_rs(lower, "gpt5.4")
            || gpt5_token_matches_rs(lower, "gpt-5-4")
            || gpt5_token_matches_rs(lower, "gpt5-4"))
    {
        return Some(CapabilityResult {
            registry_label: Some("GPT-5.4"),
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::OpenAiStandard,
        });
    }
    // rule: openai-gpt5-4, provider: databricks_v2, priority: 15
    if provider == "databricks_v2"
        && (gpt5_token_matches_rs(lower, "gpt-5.4")
            || gpt5_token_matches_rs(lower, "gpt5.4")
            || gpt5_token_matches_rs(lower, "gpt-5-4")
            || gpt5_token_matches_rs(lower, "gpt5-4"))
    {
        return Some(CapabilityResult {
            registry_label: Some("GPT-5.4"),
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::OpenAiResponses,
            normalization_policy: NormalizationPolicy::OpenAiStandard,
        });
    }
    // rule: openai-gpt5-1, provider: openai, priority: 15
    if provider == "openai"
        && (gpt5_token_matches_rs(lower, "gpt-5.1")
            || gpt5_token_matches_rs(lower, "gpt5.1")
            || gpt5_token_matches_rs(lower, "gpt-5-1")
            || gpt5_token_matches_rs(lower, "gpt5-1"))
    {
        return Some(CapabilityResult {
            registry_label: Some("GPT-5.1"),
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
            ]),
            default_effort: Some(ThinkingEffort::None),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::OpenAiStandard,
        });
    }
    // rule: openai-gpt5-1, provider: databricks_v2, priority: 15
    if provider == "databricks_v2"
        && (gpt5_token_matches_rs(lower, "gpt-5.1")
            || gpt5_token_matches_rs(lower, "gpt5.1")
            || gpt5_token_matches_rs(lower, "gpt-5-1")
            || gpt5_token_matches_rs(lower, "gpt5-1"))
    {
        return Some(CapabilityResult {
            registry_label: Some("GPT-5.1"),
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
            ]),
            default_effort: Some(ThinkingEffort::None),
            databricks_v2_wire_route: DatabricksV2Route::OpenAiResponses,
            normalization_policy: NormalizationPolicy::OpenAiStandard,
        });
    }
    // rule: anthropic-manual-budget-claude3, provider: anthropic, priority: 10
    if provider == "anthropic" && (lower.starts_with("claude-3")) {
        return Some(CapabilityResult {
            registry_label: None,
            thinking_mode: ThinkingMode::ManualBudget,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
            ]),
            default_effort: None,
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-manual-budget-claude3, provider: databricks_v2, priority: 10
    if provider == "databricks_v2" && (lower.starts_with("claude-3")) {
        return Some(CapabilityResult {
            registry_label: None,
            thinking_mode: ThinkingMode::ManualBudget,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
            ]),
            default_effort: None,
            databricks_v2_wire_route: DatabricksV2Route::AnthropicMessages,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-manual-budget-opus-4-5, provider: anthropic, priority: 10
    if provider == "anthropic" && (lower == "claude-opus-4-5") {
        return Some(CapabilityResult {
            registry_label: Some("Claude Opus 4.5"),
            thinking_mode: ThinkingMode::ManualBudget,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
            ]),
            default_effort: None,
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-manual-budget-opus-4-5, provider: databricks_v2, priority: 10
    if provider == "databricks_v2" && (lower == "claude-opus-4-5") {
        return Some(CapabilityResult {
            registry_label: Some("Claude Opus 4.5"),
            thinking_mode: ThinkingMode::ManualBudget,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
            ]),
            default_effort: None,
            databricks_v2_wire_route: DatabricksV2Route::AnthropicMessages,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-xhigh-opus-4-7, provider: anthropic, priority: 10
    if provider == "anthropic" && (lower.starts_with("claude-opus-4-7")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Opus 4.7"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-xhigh-opus-4-7, provider: databricks_v2, priority: 10
    if provider == "databricks_v2" && (lower.starts_with("claude-opus-4-7")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Opus 4.7"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::AnthropicMessages,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-xhigh-opus-4-8, provider: anthropic, priority: 10
    if provider == "anthropic" && (lower.starts_with("claude-opus-4-8")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Opus 4.8"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-xhigh-opus-4-8, provider: databricks_v2, priority: 10
    if provider == "databricks_v2" && (lower.starts_with("claude-opus-4-8")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Opus 4.8"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::AnthropicMessages,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-xhigh-opus-5, provider: anthropic, priority: 10
    if provider == "anthropic" && (lower.starts_with("claude-opus-5")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Opus 5"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-xhigh-opus-5, provider: databricks_v2, priority: 10
    if provider == "databricks_v2" && (lower.starts_with("claude-opus-5")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Opus 5"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::AnthropicMessages,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-xhigh-sonnet-5, provider: anthropic, priority: 10
    if provider == "anthropic" && (lower.starts_with("claude-sonnet-5")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Sonnet 5"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-xhigh-sonnet-5, provider: databricks_v2, priority: 10
    if provider == "databricks_v2" && (lower.starts_with("claude-sonnet-5")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Sonnet 5"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::AnthropicMessages,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-xhigh-fable-5, provider: anthropic, priority: 10
    if provider == "anthropic" && (lower.starts_with("claude-fable-5")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Fable 5"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-xhigh-fable-5, provider: databricks_v2, priority: 10
    if provider == "databricks_v2" && (lower.starts_with("claude-fable-5")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Fable 5"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::AnthropicMessages,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-xhigh-mythos-5, provider: anthropic, priority: 10
    if provider == "anthropic" && (lower.starts_with("claude-mythos-5")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Mythos 5"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-xhigh-mythos-5, provider: databricks_v2, priority: 10
    if provider == "databricks_v2" && (lower.starts_with("claude-mythos-5")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Mythos 5"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::AnthropicMessages,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-no-xhigh-opus-4-6, provider: anthropic, priority: 10
    if provider == "anthropic" && (lower.starts_with("claude-opus-4-6")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Opus 4.6"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-no-xhigh-opus-4-6, provider: databricks_v2, priority: 10
    if provider == "databricks_v2" && (lower.starts_with("claude-opus-4-6")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Opus 4.6"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::AnthropicMessages,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-no-xhigh-sonnet-4-6, provider: anthropic, priority: 10
    if provider == "anthropic" && (lower.starts_with("claude-sonnet-4-6")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Sonnet 4.6"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-no-xhigh-sonnet-4-6, provider: databricks_v2, priority: 10
    if provider == "databricks_v2" && (lower.starts_with("claude-sonnet-4-6")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Sonnet 4.6"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::AnthropicMessages,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-no-xhigh-mythos-preview, provider: anthropic, priority: 10
    if provider == "anthropic" && (lower.starts_with("claude-mythos-preview")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Mythos Preview"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: anthropic-adaptive-no-xhigh-mythos-preview, provider: databricks_v2, priority: 10
    if provider == "databricks_v2" && (lower.starts_with("claude-mythos-preview")) {
        return Some(CapabilityResult {
            registry_label: Some("Claude Mythos Preview"),
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::AnthropicMessages,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: openai-gpt5-base, provider: openai, priority: 10
    if provider == "openai"
        && (gpt5_base_matches_rs(lower, "gpt-5") || gpt5_base_matches_rs(lower, "gpt5"))
    {
        return Some(CapabilityResult {
            registry_label: Some("GPT-5"),
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Minimal,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::OpenAiStandard,
        });
    }
    // rule: openai-gpt5-base, provider: databricks_v2, priority: 10
    if provider == "databricks_v2"
        && (gpt5_base_matches_rs(lower, "gpt-5") || gpt5_base_matches_rs(lower, "gpt5"))
    {
        return Some(CapabilityResult {
            registry_label: Some("GPT-5"),
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Minimal,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::OpenAiResponses,
            normalization_policy: NormalizationPolicy::OpenAiStandard,
        });
    }
    // rule: dbv2-claude-code-names-segment, provider: databricks_v2, priority: 5
    if provider == "databricks_v2"
        && (lower
            .split(|c: char| !c.is_ascii_alphanumeric())
            .any(|s| s == "claude")
            || lower
                .split(|c: char| !c.is_ascii_alphanumeric())
                .any(|s| s == "opus")
            || lower
                .split(|c: char| !c.is_ascii_alphanumeric())
                .any(|s| s == "sonnet")
            || lower
                .split(|c: char| !c.is_ascii_alphanumeric())
                .any(|s| s == "haiku")
            || lower
                .split(|c: char| !c.is_ascii_alphanumeric())
                .any(|s| s == "mythos")
            || lower
                .split(|c: char| !c.is_ascii_alphanumeric())
                .any(|s| s == "fable"))
    {
        return Some(CapabilityResult {
            registry_label: None,
            thinking_mode: ThinkingMode::OmitFields,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::AnthropicMessages,
            normalization_policy: NormalizationPolicy::None,
        });
    }
    // rule: dbv2-gpt-code-names-segment, provider: databricks_v2, priority: 5
    if provider == "databricks_v2"
        && (lower
            .split(|c: char| !c.is_ascii_alphanumeric())
            .any(|s| s.starts_with("gpt")))
    {
        return Some(CapabilityResult {
            registry_label: None,
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Minimal,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::OpenAiResponses,
            normalization_policy: NormalizationPolicy::OpenAiClampMaxToXHigh,
        });
    }
    // rule: dbv2-sol-luna-terra-segment, provider: databricks_v2, priority: 5
    if provider == "databricks_v2"
        && (lower
            .split(|c: char| !c.is_ascii_alphanumeric())
            .any(|s| s == "sol")
            || lower
                .split(|c: char| !c.is_ascii_alphanumeric())
                .any(|s| s == "luna")
            || lower
                .split(|c: char| !c.is_ascii_alphanumeric())
                .any(|s| s == "terra"))
    {
        return Some(CapabilityResult {
            registry_label: None,
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Minimal,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::OpenAiResponses,
            normalization_policy: NormalizationPolicy::OpenAiClampMaxToXHigh,
        });
    }
    None
}

// ---------------------------------------------------------------------------
// Provider fallbacks — blank vs concrete-unknown, per provider
// ---------------------------------------------------------------------------

/// Returns the fallback capability record for the given provider and model state.
/// `is_blank` is true when the model string is empty/whitespace; false when it is
/// a nonblank but unmatched concrete ID.
pub fn provider_fallback(provider: &str, is_blank: bool) -> CapabilityResult {
    match (provider, is_blank) {
        ("anthropic", true) => CapabilityResult {
            registry_label: None,
            thinking_mode: ThinkingMode::Adaptive,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::None,
        },
        ("anthropic", false) => CapabilityResult {
            registry_label: None,
            thinking_mode: ThinkingMode::OmitFields,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::High),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::None,
        },
        ("openai", true) => CapabilityResult {
            registry_label: None,
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Minimal,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::OpenAiClampMaxToXHigh,
        },
        ("openai", false) => CapabilityResult {
            registry_label: None,
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Minimal,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::OpenAiClampMaxToXHigh,
        },
        ("databricks_v2", true) => CapabilityResult {
            registry_label: None,
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Minimal,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::RouteUnknown,
            normalization_policy: NormalizationPolicy::OpenAiClampMaxToXHigh,
        },
        ("databricks_v2", false) => CapabilityResult {
            registry_label: None,
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Minimal,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::MlflowChatCompletions,
            normalization_policy: NormalizationPolicy::OpenAiClampMaxToXHigh,
        },
        ("databricks", true) => CapabilityResult {
            registry_label: None,
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Minimal,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::OpenAiClampMaxToXHigh,
        },
        ("databricks", false) => CapabilityResult {
            registry_label: None,
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Minimal,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::OpenAiClampMaxToXHigh,
        },
        ("openrouter", true) => CapabilityResult {
            registry_label: None,
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Minimal,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::None,
        },
        ("openrouter", false) => CapabilityResult {
            registry_label: None,
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Minimal,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::None,
        },
        // Default fallback for unknown/empty providers
        (_, true) => CapabilityResult {
            registry_label: None,
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Minimal,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::None,
        },
        (_, false) => CapabilityResult {
            registry_label: None,
            thinking_mode: ThinkingMode::None,
            supported_efforts: Cow::Borrowed(&[
                ThinkingEffort::None,
                ThinkingEffort::Minimal,
                ThinkingEffort::Low,
                ThinkingEffort::Medium,
                ThinkingEffort::High,
                ThinkingEffort::XHigh,
                ThinkingEffort::Max,
            ]),
            default_effort: Some(ThinkingEffort::Medium),
            databricks_v2_wire_route: DatabricksV2Route::NotApplicable,
            normalization_policy: NormalizationPolicy::None,
        },
    }
}

// ---------------------------------------------------------------------------
// Top-level resolve — total function, always returns a complete result
// ---------------------------------------------------------------------------

/// Resolve (provider, raw_model_id) → CapabilityResult.
///
/// This is the single entry point. Result is complete — every axis is populated.
/// Consumers never compose fields from multiple tiers at runtime.
///
/// Resolution order (plan v4 resolver contract):
///   1. provider-qualified raw exact lookup (before any prefix stripping)
///   2. provider-scoped family rules on normalized alias
///   3. per-axis provider fallback (blank vs concrete-unknown)
pub fn resolve_model_capabilities(provider: &str, raw_model_id: &str) -> CapabilityResult {
    // Step 1: raw exact lookup
    if let Some(exact) = lookup_exact(provider, raw_model_id) {
        return exact;
    }

    // Step 2: family rules on normalized alias
    let normalized = strip_catalog_prefix(raw_model_id);
    if let Some(family) = lookup_by_family_rules(provider, normalized) {
        return family;
    }

    // Step 3: provider fallback
    let is_blank = raw_model_id.trim().is_empty();
    let mut fallback = provider_fallback(provider, is_blank);
    fallback.registry_label = None;
    fallback
}

// ---------------------------------------------------------------------------
// Generated constants (fold-in from #3603 branch)
// ---------------------------------------------------------------------------

/// Valid thinking-effort values accepted by buzz-agent.
/// Mirrors parse_thinking_effort in config.rs.
pub const THINKING_EFFORT_VALUES: &[&str] =
    &["none", "minimal", "low", "medium", "high", "xhigh", "max"];

/// Databricks v2 known model IDs. Mirrors goose DATABRICKS_V2_KNOWN_MODELS.
/// Single source of truth inside buzz; generated from manifest databricks_v2_known_models section.
pub const DATABRICKS_V2_KNOWN_MODELS: &[&str] = &[
    "databricks-claude-haiku-4-5",
    "databricks-claude-opus-4-1",
    "databricks-claude-opus-4-5",
    "databricks-claude-opus-4-6",
    "databricks-claude-opus-4-7",
    "databricks-claude-sonnet-4",
    "databricks-claude-sonnet-4-5",
    "databricks-claude-sonnet-4-6",
    "databricks-gemini-2-5-flash",
    "databricks-gemini-2-5-pro",
    "databricks-gemini-3-1-flash-lite",
    "databricks-gemini-3-1-pro",
    "databricks-gemini-3-flash",
    "databricks-gemini-3-pro",
    "databricks-glm-5-2",
    "databricks-gpt-5",
    "databricks-gpt-5-1",
    "databricks-gpt-5-2",
    "databricks-gpt-5-4",
    "databricks-gpt-5-4-mini",
    "databricks-gpt-5-4-nano",
    "databricks-gpt-5-5",
    "databricks-gpt-5-6-luna",
    "databricks-gpt-5-6-sol",
    "databricks-gpt-5-6-terra",
    "databricks-gpt-5-mini",
    "databricks-gpt-5-nano",
    "databricks-gpt-oss-120b",
    "databricks-gpt-oss-20b",
    "databricks-kimi-k2-7-code",
];

/// Databricks endpoint-ID to display-name registry. Generated from manifest registry_labels section.
/// Feeds the static registry tier of resolveModelLabel(). Final display label is determined
/// by the three-tier precedence in resolveModelLabel() (discovered_name > registry_label > raw_id).
pub const DATABRICKS_MODEL_NAMES: &[(&str, &str)] = &[
    ("databricks-claude-haiku-4-5", "Claude Haiku 4.5 (latest)"),
    ("databricks-claude-opus-4-1", "Claude Opus 4.1 (latest)"),
    ("databricks-claude-opus-4-5", "Claude Opus 4.5 (latest)"),
    ("databricks-claude-opus-4-6", "Claude Opus 4.6"),
    ("databricks-claude-opus-4-7", "Claude Opus 4.7"),
    ("databricks-claude-sonnet-4", "Claude Sonnet 4.5"),
    ("databricks-claude-sonnet-4-5", "Claude Sonnet 4.5 (latest)"),
    ("databricks-claude-sonnet-4-6", "Claude Sonnet 4.6"),
    ("databricks-gemini-2-5-flash", "Gemini 2.5 Flash"),
    ("databricks-gemini-2-5-pro", "Gemini 2.5 Pro"),
    (
        "databricks-gemini-3-1-flash-lite",
        "Gemini 3.1 Flash Lite Preview",
    ),
    (
        "databricks-gemini-3-1-pro",
        "Gemini 3.1 Pro Preview Custom Tools",
    ),
    ("databricks-gemini-3-flash", "Gemini 3 Flash Preview"),
    ("databricks-gemini-3-pro", "Gemini 3 Pro Preview"),
    ("databricks-glm-5-2", "GLM-5.2"),
    ("databricks-gpt-5", "GPT-5"),
    ("databricks-gpt-5-1", "GPT-5.1"),
    ("databricks-gpt-5-2", "GPT-5.2"),
    ("databricks-gpt-5-4", "GPT-5.4"),
    ("databricks-gpt-5-4-mini", "GPT-5.4 mini"),
    ("databricks-gpt-5-4-nano", "GPT-5.4 nano"),
    ("databricks-gpt-5-5", "GPT-5.5"),
    ("databricks-gpt-5-6-luna", "GPT-5.6 Luna"),
    ("databricks-gpt-5-6-sol", "GPT-5.6 Sol"),
    ("databricks-gpt-5-6-terra", "GPT-5.6 Terra"),
    ("databricks-gpt-5-mini", "GPT-5 Mini"),
    ("databricks-gpt-5-nano", "GPT-5 Nano"),
    ("databricks-gpt-oss-120b", "GPT OSS 120B"),
    ("databricks-gpt-oss-20b", "GPT OSS 20B"),
    ("databricks-kimi-k2-7-code", "Kimi K2.7 Code"),
];

// ---------------------------------------------------------------------------
// gpt5 boundary-aware token helpers (used by generated family resolver)
// ---------------------------------------------------------------------------

/// Returns true if `model` contains `token` at a word boundary (end-of-string or "-").
/// Does not match if followed immediately by a digit or letter.
/// Mirrors gpt5_token_matches in config.rs.
fn gpt5_token_matches_rs(model: &str, token: &str) -> bool {
    let lower = model;
    let tok_lower = token;
    let mut start = 0;
    loop {
        match lower[start..].find(tok_lower) {
            None => return false,
            Some(rel_idx) => {
                let abs_idx = start + rel_idx;
                let after_idx = abs_idx + tok_lower.len();
                let after_char = lower[after_idx..].chars().next();
                match after_char {
                    None | Some('-') => return true,
                    _ => start = after_idx,
                }
            }
        }
    }
}

/// Like gpt5_token_matches_rs but also rejects short -<1-3 digit> suffixes.
fn gpt5_base_matches_rs(model: &str, token: &str) -> bool {
    let lower = model;
    let tok_lower = token;
    let mut start = 0;
    loop {
        match lower[start..].find(tok_lower) {
            None => return false,
            Some(rel_idx) => {
                let abs_idx = start + rel_idx;
                let after_idx = abs_idx + tok_lower.len();
                let suffix = &lower[after_idx..];
                if suffix.is_empty() {
                    return true;
                }
                if !suffix.starts_with('-') {
                    start = after_idx;
                    continue;
                }
                let dash_rest = &suffix[1..];
                // Reject -<1-3 digits> that look like version numbers.
                let is_short_version =
                    dash_rest.chars().take(4).enumerate().all(|(i, c)| {
                        if i < 3 {
                            c.is_ascii_digit()
                        } else {
                            !c.is_ascii_alphanumeric()
                        }
                    }) && dash_rest.chars().next().is_some_and(|c| c.is_ascii_digit());
                if is_short_version {
                    start = after_idx;
                    continue;
                }
                return true;
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
#[path = "generated_model_capabilities_tests.rs"]
mod tests;
